# Generated by Django 6.1 on 2026-08-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationgoal',
            name='current_progress',
        ),
        migrations.AddField(
            model_name='preparationgoal',
            name='target_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_goals', to='taxonomy.tag'),
        ),
        migrations.AlterField(
            model_name='preparationgoal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparationgoal',
            name='metric',
            field=models.CharField(choices=[('question_count', 'Question Count'), ('topic_mastery', 'Topic Mastery'), ('company_target', 'Company Target')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preparationgoal',
            name='target_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_goals', to='taxonomy.company'),
        ),
        migrations.AlterField(
            model_name='preparationgoal',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparationgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProgressRecord',
        ),
    ]
