# Generated by Django 6.1 on 2026-08-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_body_question_description_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='taxonomy.tag'),
        ),
    ]
