# Generated by Django 6.1 on 2026-08-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author_id',
            new_name='author',
        ),
    ]
