# Generated by Django 6.1 on 2026-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_userquestionstatus'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='questions', to='taxonomy.tag'),
        ),
    ]
