# Generated by Django 6.1 on 2026-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_tag_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending_Review'), ('published', 'Published'), ('removed', 'Removed')], default='published', max_length=20),
        ),
    ]
