# Generated by Django 6.1 on 2026-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
