# Generated by Django 6.1 on 2026-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationreport_delete_moderatoractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationreport',
            name='action',
            field=models.CharField(choices=[('dismiss', 'Dismiss'), ('edit', 'Edit'), ('remove', 'Remove')], max_length=20),
        ),
    ]
